version: '3'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'abcd'
      MYSQL_DATABASE: TEST_DATABASE
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: munsunouk/wemade_challange:test
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
